volumes:
  rs-kafka-data-vol:
  rs-kafka-secrets-vol:
  rs-kafka-config-vol:
  rs-kafkamap-vol:

networks:
  kafka-net:
    driver: bridge

services:
  rs-kafka:
    image: apache/kafka:latest
    container_name: kafka0
    hostname: kafka0
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Shanghai
      # 必须设置唯一的 cluster ID（首次启动前生成）
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "CONTROLLER://:9093,PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka0:19092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "0@kafka0:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs" # 数据存储路径（可持久化）
    volumes:
      - rs-kafka-data-vol:/var/lib/kafka/data
      - rs-kafka-secrets-vol:/etc/kafka/secrets
      - rs-kafka-config-vol:/mnt/shared/config

  # Kafka GUI Management
  rs-kafka-map:
    image: dushixiang/kafka-map
    container_name: kafka-map
    networks:
      - kafka-net
    ports:
      - "9090:8080"
    volumes:
      - rs-kafkamap-vol:/usr/local/kafka-map/data
    environment:
      - TZ=Asia/Shanghai
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=1q2w3e4r5t
    depends_on:
      - rs-kafka

