services:
  rs-nginx:
    image: nginx:alpine
    container_name: rs-nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
