networks:
  net_rocketmq:
    driver: bridge

volumes:
  rocket-namesrv-log-vol:
  rocket-broker-log-vol:
  rocket-broker-store-vol:
  rocket-proxy-log-vol:
  rocket-dashboard-vol:

services:
  # 组件注册中心
  rocket-namesrv:
    image: ${ROCKET_IMAGE}
    container_name: rocket-namesrv
    networks:
      - net_rocketmq
    ports:
      - "9876:9876"
    # environment:
    #   - JAVA_OPT_EXT=-Xms256m -Xmx512m
    volumes:
      - rocket-namesrv-log-vol:/home/rocketmq/logs
    command: ["sh", "mqnamesrv"]
  # 消息中转
  rocket-broker:
    image: ${ROCKET_IMAGE}
    container_name: rocket-broker
    networks:
      - net_rocketmq
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=rocket-namesrv:9876
      # - JAVA_OPT_EXT=-Xms512m -Xmx768m
    volumes:
      - rocket-broker-log-vol:/home/rocketmq/logs
      - rocket-broker-store-vol:/home/rocketmq/store
      - ./broker.conf:/home/rocketmq/rocketmq-5.4.0/conf/broker.conf
    command:
      ["sh", "mqbroker", "-c", "/home/rocketmq/rocketmq-5.4.0/conf/broker.conf"]
    depends_on:
      - rocket-namesrv
  # 服务代理
  rocket-proxy:
    image: ${ROCKET_IMAGE}
    container_name: rocket-proxy
    networks:
      - net_rocketmq
    ports:
      - "9880:8080"
      - "9881:8081"
    environment:
      - NAMESRV_ADDR=rocket-namesrv:9876
      # - JAVA_OPT_EXT=-Xms256m -Xmx320m
    volumes:
      - rocket-proxy-log-vol:/home/rocketmq/logs
    depends_on:
      - rocket-broker
      - rocket-namesrv
    command: ["sh", "-c", "sleep 15 && sh mqproxy"]
  # 服务看板
  rocket-dashboard:
    image: ${DASHBOARD_IMAGE}
    container_name: rocket-dashboard
    networks:
      - net_rocketmq
    ports:
      - "9899:8082"
    environment:
      - NAMESRV_ADDR=rocket-namesrv:9876
      - JAVA_OPT=-Xms128m -Xmx256m -Drocketmq.namesrv.addr=rocket-namesrv:9876
    volumes:
      - rocket-dashboard-vol:/tmp
    depends_on:
      - rocket-namesrv
